### ISSUE TITLE
Ensure works cross platform

### ISSUE THREAD

**Issue by riggerthegeek** [PiOven/builder#15]
The current NodeJS (https://github.com/PiOven/builder/blob/master/Dockerfile#L8) doesn't run on a Pi.

**Comment by ekawahyu** [comment]
Have this issue been solved? Question, is the reason of adding Docker for having NodeJS to work cross platform?

**Comment by riggerthegeek** [comment]
Basically, yes. I wanted to be able to get it to build on OpenFAAS which I run on a cluster of Pis - this is only for the AMD64 chip, not the ARM.

This is something I want to rewrite into native code so it works truly cross platform (why I accepted #21 as it's a good improvement for future), but it's not really a priority for me at the moment.

**Comment by ekawahyu** [comment]
FYI, I started a branch that basically remove Docker off the build. I don't know if this is the right thing to do, but I know that it can be done without Docker. The other thing is that, I keep user pi as an option, but with (forced) random password.

**Comment by riggerthegeek** [comment]
@ekawahyu there's nothing stopping you from keeping the user as `pi`, just specify that in your settings.

This now been improved with a new major version which is available on [GitLab](https://gitlab.com/pi-oven/builder)
