### ISSUE TITLE
Raspberry pi is asking for password on ssh

### ISSUE THREAD

**Issue by Jacobh2** [PiOven/builder#16]
Hi!

Thank you for a very nice project! I'm hoping to make nice use of it!

I'm trying it out right now, and I am able to setup and build an image. I then use [etcher-cli](https://etcher.io/cli/) to copy it to my sdcard.

But then I run into some issues:

1. The IP of the pi is not between the ranges that I set during `make setup`. This is not a big issue, just a question if it is on "best effort" basis those ranges are given?

2. The bigger issue is that I'm unable to ssh into the pi. I'm trying using
```
ssh -i dist/ssh-keys/<name-of-private-key> <username>@<ip>
```
but it seems to not take it and instead I'm shown
```
<username>@<ip>'s password:
```

At first I tried to only supply the path to the folder where the ssh-keys are located (`/builder/dist/ssh-key`), but then I was given this:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0755 for 'ssh-keys' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "ssh-keys": bad permissions
```
so I did `chmod 600 ssh-keys`, but that just gave me:
```
Load key "./ssh-keys": Is a directory
```
So i figured I need to provide the complete path to the private key. That is when I am prompted for the password.

I tried with the password that was printed at the end of the `make build` script, but that password did not seem to work: `Permission denied, please try again.`.

Any ideas of what I'm missing here?

**Comment by Jacobh2** [comment]
Sorry about this, I was totally my fault: had misspelled the username which I did not see! Rebuilding the image with an easier username just to test made me realise this and it now works. 

However, now I ran into another issue which seems to be a little more serious. Also seems to be related to #8 but I'm getting another error message:

```
Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l
-sh: 7: /etc/profile.d/motd.sh: Syntax error: "(" unexpected
$
```

I'm guessing the reason for this is as @riggerthegeek [said in that issue](https://github.com/PiOven/builder/issues/8#issuecomment-381312290) about different baseimages: I'm also using another image than he did. For the `make setup` I'm entering `https://downloads.raspberrypi.org/raspbian_lite_latest`, which as of writing this is `2018-06-27-raspbian-stretch-lite.img`.

**Comment by riggerthegeek** [comment]
I wouldn't use the latest issue as there are various issues with different OS versions that need better testing. If you need to use it, use the default OS version when you run `make setup`.

PRs welcome if you figure out how to fix this.

**Comment by stevanikof** [comment]
Looks like the default shell is /bin/sh in raspbian Stretch
So you need to create the user with bash shell specified
suggested edit:
`diff --git a/scripts/first_run.sh b/scripts/first_run.sh
index 935adba..70a8592 100644
--- a/scripts/first_run.sh
+++ b/scripts/first_run.sh
@@ -9,7 +9,7 @@ set -e
 DATA_DIR=/opt/data
 
 # Delete "pi" user and create another one
-useradd -m %PI_USERNAME% -G sudo || true
+useradd -m %PI_USERNAME% -G sudo -s /bin/bash || true
 echo "%PI_USERNAME%:%PI_PASSWORD%" | chpasswd
 install -d -m 700 /home/%PI_USERNAME%/.ssh
 mv /id_rsa.pub /home/%PI_USERNAME%/.ssh/authorized_keys
`
