### ISSUE TITLE
[FIXED] /dev/loop bad address

### ISSUE THREAD

**Issue by ekawahyu** [PiOven/builder#20]
@riggerthegeek I have the fix for the pibuilder.sh as follows:

https://github.com/ekawahyu/pioven-builder/commit/a3499beadd75f512ffe648a6c792fb0c73f2ae6c

I tested everything to work, even without the `sleep`. But I kept it in there, shorter.

**Comment by riggerthegeek** [comment]
Do you want to raise a pull request for this?

**Comment by ekawahyu** [comment]
I did not raise a pull request cause I am not sure about the sleep time changes in there, but yes I can do pull request.

**Comment by ekawahyu** [comment]
Pull request is on its way, closing this issue. Thank you.
