### ISSUE TITLE
Shorter password

### ISSUE THREAD

**Issue by nhippenmeyer** [PiOven/builder#9]
I'd like to have the option of generating a shorter password (8 characters instead of the default 32).  Do you think it makes sense to add the password length as a variable in the `settings.sh` file?  If so I'm happy to open a PR with the necessary changes.

**Comment by riggerthegeek** [comment]
Seems a good idea to me. I'd like to keep the random 32 character password as the default (to encourage logging in with SSH keys), but I don't fundamentally object to someone specifying their own password or a shorter random password.

**Comment by riggerthegeek** [comment]
Fixed with #11
